#!/bin/bash
set -e
set -v

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc

VAULT_VERSION=1.7.4
TERRAFORM_VERSION=1.0.7
CONSUL_VERSION=1.10.2

# Install Vault
curl -fsSL -o /tmp/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}+ent/vault_${VAULT_VERSION}+ent_linux_amd64.zip
unzip -o -d /usr/local/bin/ /tmp/vault.zip

# Install Terraform
curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
unzip -o -d /usr/local/bin/ /tmp/terraform.zip

# Install Consul
curl -fsSL -o /tmp/consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
unzip -o -d /usr/local/bin/ /tmp/consul.zip

cd /tmp
git clone https://github.com/Andrew-Klaas/instruqt-zt-lab.git

# Copy additional files.
cp instruqt-zt-lab/assets/systemd-files/envoy /usr/local/bin/envoy
cp instruqt-zt-lab/assets/systemd-files/consul.service /etc/systemd/system/consul.service

mkdir /etc/consul.d
mkdir /tmp/consul

systemctl daemon-reload
systemctl enable consul.service

####################################
# Configure Consul Server
####################################
HOST_IP_ADDR=$(ifconfig ens4 | grep "inet " | awk '{ print$2 }')
cat << EOF > /etc/consul.d/consul.hcl
datacenter = "dc1"
retry_join = ["hashistack-server"]
retry_interval = ["5s"]
data_dir = "/tmp/consul"
server = false
log_level = "INFO"
node_name = "hashistack-client-2"
client_addr = "$HOST_IP_ADDR"
bind_addr = "$HOST_IP_ADDR"
ui = true
ports {
  grpc = 8502
}
connect {
  enabled = true
}
EOF

apt update -y 
apt install -y dnsmasq
sed -i '1i nameserver 127.0.0.1\n' /etc/resolv.conf
bash -c "cat >/etc/dnsmasq.d/10-consul" << EOF
server=/consul/$HOST_IP_ADDR#8600
EOF

systemctl start consul
systemctl enable dnsmasq
sleep 10s
systemctl restart systemd-resolved
systemctl restart dnsmasq

echo "Consul install complete" >> /tmp/install.log

####################################
# Configure PostgreSQL
####################################

sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
apt-get -y update
sudo apt-get -y install postgresql
sudo cat << EOF > /etc/postgresql/14/main/conf.d/postgresql.conf
listen_addresses '*'
EOF
sudo echo "
host    all             all              0.0.0.0/0                       md5
host    all             all              ::/0                            md5
" >> /etc/postgresql/14/main/pg_hba.conf
systemctl start postgresql

sudo -u postgres psql << EOF
ALTER USER postgres PASSWORD 'password';
CREATE DATABASE vault_go_demo;
EOF

###################################
# PostgreSQL Consul / Envoy 
###################################
sudo cat << EOF > /etc/consul.d/postgres.hcl 
service {
  name = "postgres"
  tags = [ "postgres" ]
  port = 5432
  connect {
    sidecar_service {
      proxy {
        config {
          protocol = "tcp"
        }
      }
    }
  }
  check {
    id       = "postgresql-check"
    tcp      = "127.0.0.1:5432"
    interval = "10s"
  }
}
EOF

sudo service consul restart

sleep 5s

nohup consul connect envoy --sidecar-for postgres nohup.out 2> nohup.err < /dev/null & disown

