#!/bin/bash
set -e
set -v

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc

VAULT_VERSION=1.7.4
TERRAFORM_VERSION=1.0.7
CONSUL_VERSION=1.10.2
BOUNDARY_VERSION=0.6.1

# Install Vault
curl -fsSL -o /tmp/vault.zip https://releases.hashicorp.com/vault/${VAULT_VERSION}+ent/vault_${VAULT_VERSION}+ent_linux_amd64.zip
unzip -o -d /usr/local/bin/ /tmp/vault.zip

# Install Terraform
curl -fsSL -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
unzip -o -d /usr/local/bin/ /tmp/terraform.zip

# Install Consul
curl -fsSL -o /tmp/consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
unzip -o -d /usr/local/bin/ /tmp/consul.zip

# Install Boundary
curl -fsSL -o /tmp/boundary.zip https://releases.hashicorp.com/boundary/${BOUNDARY_VERSION}/boundary_${BOUNDARY_VERSION}_linux_amd64.zip
unzip -o -d /usr/local/bin/ /tmp/boundary.zip

cd /tmp
git clone https://github.com/Andrew-Klaas/instruqt-zt-lab.git

# Copy additional files.
cp instruqt-zt-lab/assets/systemd-files/envoy /usr/local/bin/envoy
cp instruqt-zt-lab/assets/systemd-files/consul.service /etc/systemd/system/consul.service
cp instruqt-zt-lab/assets/systemd-files/vault.service /etc/systemd/system/vault.service
cp instruqt-zt-lab/assets/systemd-files/boundary-controller.service /etc/systemd/system/boundary-controller.service
cp instruqt-zt-lab/assets/systemd-files/boundary-worker.service /etc/systemd/system/boundary-worker.service
cp instruqt-zt-lab/assets/systemd-files/boundary.service /etc/systemd/system/boundary.service

mkdir /etc/consul.d
mkdir /etc/vault.d
mkdir /etc/boundary.d
mkdir /tmp/consul
mkdir /tmp/vault
mkdir /tmp/boundary

systemctl daemon-reload
systemctl enable consul.service
systemctl enable vault.service
systemctl enable boundary-controller.service
systemctl enable boundary-worker.service

####################################
# Configure Consul Server
####################################
HOST_IP_ADDR=$(ifconfig ens4 | grep "inet " | awk '{ print$2 }')
cat << EOF > /etc/consul.d/consul.hcl
datacenter = "dc1"
data_dir = "/tmp/consul"
server = true
log_level = "INFO"
node_name = "server"
bootstrap_expect = 1
client_addr = "$HOST_IP_ADDR"
bind_addr = "$HOST_IP_ADDR"
ui = true
connect {
  enabled = true
}
EOF

apt update -y 
apt install -y dnsmasq
sed -i '1i nameserver 127.0.0.1\n' /etc/resolv.conf
bash -c "cat >/etc/dnsmasq.d/10-consul" << EOF
server=/consul/$HOST_IP_ADDR#8600
EOF

systemctl start consul
systemctl enable dnsmasq
sleep 10s
systemctl restart systemd-resolved
systemctl restart dnsmasq


echo "Consul install complete" >> /tmp/install.log

####################################
# Configure Vault Server
####################################
cat << EOF > /etc/vault.d/vault.hcl
storage "file" {
  path = "/tmp/vault/data"
}
listener "tcp" {
  address     = "0.0.0.0:8200"
  tls_disable = 1
}
# service_registration "consul" {
#   address = "$HOST_IP_ADDR:8500"
# }
api_addr = "http://$HOST_IP_ADDR:8200"
cluster_addr = "https://$HOST_IP_ADDR:8201"
ui = true
EOF

systemctl start vault

sleep 5s

vault operator init -key-shares=1  -key-threshold=1 --format json >> init.txt
ROOT_TOKEN=$(cat init.txt | jq -r .root_token)
UNSEAL_KEY=$(cat init.txt | jq -r .unseal_keys_b64[0])

vault operator unseal $UNSEAL_KEY
vault login $ROOT_TOKEN

#Create admin user
echo '
path "*" {
    capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}' | vault policy write vault_admin -
vault auth enable userpass
vault write auth/userpass/users/vault password=vault policies=vault_admin

vault secrets enable transform
vault write transform/role/vault_go_demo transformations=ssn
vault write transform/transformations/tokenization/ssn \
    allowed_roles=vault_go_demo \
    max_ttl=24h

echo "Vault install complete" >> /tmp/install.log

####################################
# Configure Boundary Server
####################################



cat << EOF > /etc/boundary.d/boundary.hcl
disable_mlock = true
controller {
  # This name attr must be unique across all controller instances if running in HA mode
  name = "demo-controller-1"
  description = "A controller for a demo!"
  # Database URL for postgres. This can be a direct "postgres://"
  # URL, or it can be "file://" to read the contents of a file to
  # supply the url, or "env://" to name an environment variable
  # that contains the URL.
  database {
      url = "postgresql://boundary:boundarydemo@postgres.yourdomain.com:5432/boundary"
  }
}
# API listener configuration block
listener "tcp" {
  # Should be the address of the NIC that the controller server will be reached on
  address = "10.0.0.1"
  # The purpose of this listener block
  purpose = "api"
  tls_disable = false
  # Uncomment to enable CORS for the Admin UI. Be sure to set the allowed origin(s)
  # to appropriate values.
  #cors_enabled = true
  #cors_allowed_origins = ["https://yourcorp.yourdomain.com", "serve://boundary"]
}
# Data-plane listener configuration block (used for worker coordination)
listener "tcp" {
  # Should be the IP of the NIC that the worker will connect on
  address = "10.0.0.1"
  # The purpose of this listener
  purpose = "cluster"
}
kms "aead" {
  purpose = "root"
  aead_type = "aes-gcm"
  key = "sP1fnF5Xz85RrXyELHFeZg9Ad2qt4Z4bgNHVGtD6ung="
  key_id = "global_root"
}
kms "aead" {
  purpose = "worker-auth"
  aead_type = "aes-gcm"
  key = "8fZBjCUfN0TzjEGLQldGY4+iE9AkOvCfjh7+p0GtRBQ="
  key_id = "global_worker-auth"
}
kms "aead" {
  purpose = "recovery"
  aead_type = "aes-gcm"
  key = "8fZBjCUfN0TzjEGLQldGY4+iE9AkOvCfjh7+p0GtRBQ="
  key_id = "global_recovery"
}
EOF





