#!/bin/bash
set -e
set -v

until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc

VAULT_VERSION=1.7.4
TERRAFORM_VERSION=1.0.7
CONSUL_VERSION=1.10.2

# Install Vault
curl -fsSL -o /tmp/vault.zip "https://releases.hashicorp.com/vault/${VAULT_VERSION}+ent/vault_${VAULT_VERSION}+ent_linux_amd64.zip"
unzip -o -d /usr/local/bin/ /tmp/vault.zip

# Install Terraform
curl -fsSL -o /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
unzip -o -d /usr/local/bin/ /tmp/terraform.zip

# Install Consul
curl -fsSL -o /tmp/consul.zip "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip"
unzip -o -d /usr/local/bin/ /tmp/consul.zip

cd /tmp
git clone https://github.com/Andrew-Klaas/instruqt-zt-lab.git

# Copy additional files.
ENVOY_VERSION="1.18.3"
wget "https://archive.tetratelabs.io/envoy/download/v${ENVOY_VERSION}/envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz"
tar -xf envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz
chmod +x envoy-v${ENVOY_VERSION}-linux-amd64/bin/envoy
mv envoy-v${ENVOY_VERSION}-linux-amd64/bin/envoy /usr/local/bin/envoy
rm -rf envoy-v${ENVOY_VERSION}-linux-amd64.tar.xz envoy-v${ENVOY_VERSION}-linux-amd64

cp instruqt-zt-lab/assets/systemd-files/consul.service /etc/systemd/system/consul.service
cp instruqt-zt-lab/assets/systemd-files/goapp.service /etc/systemd/system/goapp.service

mkdir /etc/consul.d
mkdir /tmp/consul

systemctl daemon-reload
systemctl enable consul.service

####################################
# Configure Consul Server
####################################
HOST_IP_ADDR=$(ifconfig ens4 | grep "inet " | awk '{ print$2 }')
cat << EOF > /etc/consul.d/consul.hcl
datacenter = "dc1"
retry_join = ["hashistack-server"]
retry_interval = ["5s"]
data_dir = "/tmp/consul"
server = false
log_level = "DEBUG"
node_name = "hashistack-client-1"
client_addr = "$HOST_IP_ADDR 127.0.0.1"
bind_addr = "$HOST_IP_ADDR"
ui = true
ports {
  grpc = 8502
}
EOF

apt update -y 
apt install -y dnsmasq
sed -i '1i nameserver 127.0.0.1\n' /etc/resolv.conf
bash -c "cat >/etc/dnsmasq.d/10-consul" << EOF
server=/consul/$HOST_IP_ADDR#8600
EOF

systemctl start consul
systemctl enable dnsmasq
sleep 10s
systemctl restart systemd-resolved
systemctl restart dnsmasq

echo "Consul install complete" >> /tmp/install.log

####################################
# Golang Application
####################################

sudo cat << EOF > /etc/consul.d/goapp.hcl 
service {
  name = "goapp"
  tags = [ "goapp" ]
  port = 9090
  connect {
    sidecar_service {
      proxy {
        upstreams = [
          {
            destination_name = "postgres"
            local_bind_port  = 5432
          }
        ]
      }
    }
  }
}
EOF

sudo systemctl restart consul

sleep 5s

nohup consul connect envoy --sidecar-for goapp > nohup.out 2> nohup.err < /dev/null & disown

apt-get install -y golang
git clone https://github.com/Andrew-Klaas/aws-vault-go-demo-tokenization.git

sudo mkdir -p /root/.aws
sudo cat << EOF > /root/.aws/credentials
[default]
aws_access_key_id=$AWS_ACCESS_KEY_ID
aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
EOF

systemctl enable goapp.service
sleep 1
systemctl restart goapp

exit 0
